// MARK: - Header

//
//  FakeBundle.swift
//
//  Generated by FakeBundle
//  See https://github.com/zweigraf/FakeBundle
//

import Foundation

protocol FileType {
    var isDirectory: Bool { get }
    var filename: String { get }
    func export(to path: String) throws
}
protocol File: FileType {
    var contentsBase64: String { get }
}
extension File {
    var isDirectory: Bool {
        return false
    }
    var contents: Data? {
        return Data(base64Encoded: contentsBase64)
    }
    
    func export(to path: String) throws {
        guard let contents = contents else { return }
        let originalUrl = URL(fileURLWithPath: path)
        let myUrl = originalUrl.appendingPathComponent(filename)
        try contents.write(to: myUrl)
    }
}
protocol Directory: FileType {
    var children: [FileType] { get }
}
extension Directory {
    var isDirectory: Bool {
        return true
    }
    func export(to path: String) throws {
        let originalUrl = URL(fileURLWithPath: path)
        let myUrl = originalUrl.appendingPathComponent(filename)
        try FileManager.default.createDirectory(at: myUrl, withIntermediateDirectories: true, attributes: nil)
        try children.forEach { try $0.export(to: myUrl.path) }
    }
}

// MARK: - Dynamic Code

func makeDirectory(name: String, filename: String, childrenCreation: String, childrenClasses: String) -> String {
    return """
    class \(name): Directory {
        var filename: String = "\(filename)"
        lazy var children: [FileType] = {
            return [\(childrenCreation)]
        }()
    
        \(childrenClasses)
    }
    """
}

func makeFile(name: String, filename: String, contentsBase64: String) -> String {
    return """
    class \(name): File {
        var filename: String = "\(filename)"
        lazy var contentsBase64: String = {
            return "\(contentsBase64)"
        }()
    }
    """
}
